imageSrc: "assets/images/DjHippoATL1.png"
textContent: >-
  Dj Hippo is the stage name of Mike Borrebach, based out of Seattle, WA.
  Being one of only a handful of touring DJs that don’t have any original music released,
  he has made a name for himself by uniquely mashing up an eclectic array of bass music,
  ranging from melodic drifting soundscapes to floor shaking bangers. His sets focus on
  seamless transitions and continuous mash-ups, constantly keeping the audience on
  their toes with familiar tunes mashed with unknown oddities.


  He has shared the stage with some of the best acts in bass music, including G Jones,
  Luczid, and Jantsen, while headlining numerous shows across the country.
  Originally gaining notoriety for his Bassnectar inspired mixtapes, he has since
  earned his spot among the most talented mix artists out there today.
