socials:
  - icon: assets/images/fbk.svg
    link: https://www.facebook.com/djhippobassmusic/
  - icon: assets/images/inst.svg
    link: https://www.instagram.com/dj_hippo_/
  - icon: assets/images/twi.svg
    link: https://twitter.com/__djhippo__
  - icon: assets/images/soundcloud.svg
    link: https://soundcloud.com/dj_hippo
