socials:
  - icon: assets/images/facebook.png
    link: https://www.facebook.com/djhippobassmusic/
  - icon: assets/images/instagram.png
    link: https://www.instagram.com/dj_hippo_/
  - icon: assets/images/twitter.png
    link: https://twitter.com/__djhippo__
  - icon: assets/images/soundcloud.png
    link: https://soundcloud.com/dj_hippo
