events:
  - date: 20190420
    name: High Times III
    location: Philadelphia, PA
    event: https://www.facebook.com/events/423341735088792/
    tickets: dummyLink.com
  - date: 20190422
    name: High Times III
    location: Philadelphia, PA
    event: https://www.facebook.com/events/423341735088792/
  - date: 20190422
    name: High Times III
    location: Philadelphia, PA
  - date: 20190422
    name: High Times III
    location: Philadelphia, PA
    event: https://www.facebook.com/events/423341735088792/
  - date: 20190422
    name: High Times III
    location: Philadelphia, PA
    event: https://www.facebook.com/events/423341735088792/
  - date: 20190422
    name: High Times III
    location: Philadelphia, PA
    event: https://www.facebook.com/events/423341735088792/
  - date: 20190422
    name: High Times III
    location: Philadelphia, PA
    event: https://www.facebook.com/events/423341735088792/
  - date: 20190422
    name: High Times III
    location: Philadelphia, PA
    event: https://www.facebook.com/events/423341735088792/
  - date: 20190422
    name: High Times III
    location: Philadelphia, PA
    event: https://www.facebook.com/events/423341735088792/